spring:
  application:
    name: internet-service-provider
  servlet:
    multipart:
      max-file-size: 500MB
    max-request-size: 500MB

server:
  port: 8090

app:
  image:
    save:
      location: local
